# Generated by Django 4.2.16 on 2026-03-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300)),
                ('description', models.TextField()),
                ('requirements', models.TextField(blank=True)),
                ('project_type', models.CharField(choices=[('internship', 'Internship'), ('research', 'Research'), ('part_time', 'Part-Time'), ('full_time', 'Full-Time'), ('freelance', 'Freelance'), ('capstone', 'Capstone')], db_index=True, default='internship', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('completed', 'Completed')], db_index=True, default='open', max_length=20)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('stipend', models.CharField(blank=True, max_length=100)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated: Python, React, ML')),
                ('max_applicants', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
    ]
