# Generated by Django 4.2.16 on 2026-04-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('projects', '0003_savedproject'),
    ]

    operations = [
    ]
