# Generated by Django 4.2.16 on 2026-04-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_email_verification_password_reset_tokens'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='facultyprofile',
            name='research_interests',
            field=models.TextField(blank=True),
        ),
    ]
