# Generated by Django 4.2.16 on 2026-04-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_and_more'),
        ('users', '0004_passwordresettoken_add_used_field'),
    ]

    operations = [
    ]
